LOCAL_PATH:= $(call my-dir)

include $(CLEAR_VARS)

LOCAL_MODULE        := NubiaCamera
LOCAL_MODULE_TAGS   := optional
LOCAL_MODULE_CLASS  := APPS
LOCAL_MODULE_OWNER  := nubia
LOCAL_MODULE_SUFFIX := $(COMMON_ANDROID_PACKAGE_SUFFIX)
LOCAL_SRC_FILES     := NubiaCamera.apk
LOCAL_CERTIFICATE   := shared
LOCAL_OVERRIDES_PACKAGES := Camera2

include $(BUILD_PREBUILT)
